### ISSUE TITLE
Pictionary app.py: TypeError: must be real number, not dict

### ISSUE THREAD

**Issue by drscotthawley** [nateraw/gradio-guides#1]
Dear Nate,

I found this repo after seeing the gradio documentation on  ["Building a Pictionary App"](https://www.gradio.app/3.50.2/guides/building-a-pictionary-app#1-set-up-the-sketch-recognition-model).  
I wonder if something might have changed in the two years since you wrote it.   When draw something and press the little check mark, I get  this behavior: 

```python
$ python app.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/gradio/utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/shawley/hs/mnist-toy/app.py", line 32, in predict
    x = torch.tensor(im, dtype=torch.float32).unsqueeze(0).unsqueeze(0) / 255.0
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not dict
```

It looks like the "im" coming from SketchPad is no longer an array but rather a dict with keys "background", "layers", and "composite".  
I tried adding a `im = im['composite']` before the `x = ` line above, but then the shapes aren't coming out correctly: 

```python
  File "/Users/shawley/envs/hs/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 600, 800, 4]```
```

So then I thought, ok what if we just take the [0] (or [0][0]) component of that?  But... that wasn't working either.  I tried a few other shape-changing operations but couldn't get anything to work. 

Wondering if you or anyone involved with `gradio` could suggest a fix to update this demo code? 

Thanks.

**Comment by drscotthawley** [comment]
Ah, the fix is to downgrade to an earlier version of `gradio`.  The version is listed in the same docs, I just hadn't imagined such a drastic change. 

So then, the fix is: 
```bash
$ pip install gradio==3.50.2
...
  Attempting uninstall: gradio
    Found existing installation: gradio 4.16.0
    Uninstalling gradio-4.16.0:
      Successfully uninstalled gradio-4.16.0
Successfully installed gradio-3.50.2 gradio-client-0.6.1
```
